# Generated by Django 4.0.6 on 2022-07-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('display', models.BooleanField()),
            ],
        ),
    ]
