# Generated by Django 4.0.7 on 2022-08-25 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import photos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(db_index=True, max_length=20, verbose_name='Город')),
                ('city_code', models.IntegerField(default=0, unique=True, verbose_name='Код города')),
                ('operators', models.ManyToManyField(related_name='cities', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['city_name'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('journal_name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Название журнала')),
                ('total_pages', models.IntegerField(default=33, editable=False, null=True, verbose_name='Всего страниц')),
                ('filled_pages', models.IntegerField(default=0, editable=False, null=True, verbose_name='Заполнено страниц')),
                ('journal_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.city', verbose_name='Город')),
                ('journal_owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
                'ordering': ['journal_city', 'journal_name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_image', models.ImageField(default='', upload_to=photos.models.photo_path, verbose_name='Изображение')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('photo_name', models.CharField(blank=True, default='', max_length=20, verbose_name='Название')),
                ('page_in_journal', models.IntegerField(default=0, editable=False, verbose_name='Номер страницы в журнале')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.journal', verbose_name='Журнал')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['page_in_journal'],
            },
        ),
    ]
